awesome_poll_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'awesome_polls_site'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^registration/', include('registration.urls'))
]

polls/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'polls'

urlpatterns = [
    # ../polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name="results"),
    # ../polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.VoteView.as_view(), name="vote"),
    # ../polls/addquestion/
    url(r'^addpoll/$', views.AddPollView.as_view(), name="add_poll"),
    url(r'^trymustache/$', views.TryMustacheView.as_view(), name="try_mustache"),
    url(r'^mainmustache/$', views.MainMustacheView.as_view(), name="main_mustache")
]

registration/urls.py
from django.conf.urls import url

from registration import views

app_name = 'registration'

urlpatterns = [
    url(r'^login/$', views.LogInView.as_view(), name='log_in'),
    url(r'^signup/$', views.SignUpView.as_view(), name='sign_up'),
    url(r'^editprofile/$', views.EditProfileView.as_view(), name='edit_profile'),
    url(r'^logout/$', views.LogOutView.as_view(), name='log_out')
]

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date Published')
    user_who_asked = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class PollVote(models.Model):
    user_who_voted = models.ForeignKey(User, on_delete=models.CASCADE)
    question_which_is_voted = models.ForeignKey(Question, on_delete=models.CASCADE)

awesome_poll_site/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from polls import views
from polls.models import Question

class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = 'registration:log_in'
    redirect_field_name = 'redirect_to'

    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now(),
        ).order_by('-pub_date')[:10]

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core import serializers

from .models import Question, Choice, PollVote


class ResultsView(LoginRequiredMixin, generic.DetailView):
    login_url = 'registration:log_in'
    redirect_field_name = 'redirect_to'
    
    model = Question
    template_name = 'polls/results.html'


class VoteView(LoginRequiredMixin, generic.TemplateView):
    login_url = 'registration:log_in'
    redirect_field_name = 'redirect_to'

    def post(self, request, question_id, *args, **kwargs):
        question = get_object_or_404(Question, pk=question_id)
    
        poll_vote = PollVote.objects.filter(user_who_voted=request.user, question_which_is_voted=question)            
        
        if poll_vote.exists():
            return render(request, 'polls/results.html', {
                'question' : question,
                'error_message' : "You already voted here."
            })

        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
            
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'polls/results.html', {
                'question' : question,
                'error_message' : "You didn't select a choice."
            })

        else:
            selected_choice.votes += 1
            selected_choice.save()

            PollVote.objects.create(user_who_voted=request.user, question_which_is_voted=question)

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class AddPollView(LoginRequiredMixin, generic.TemplateView):
    login_url = 'registration:log_in'
    redirect_field_name = 'redirect_to'

    template_name = 'polls/addpoll.html'

    def post(self, request, *args, **kwargs):
        question_text = request.POST.get('question_text')
        question = Question.objects.create(question_text=question_text, pub_date=timezone.now(), user_who_asked=request.user)

        i = 0
        while request.POST.get('item' + str(i)) != None:
            choice_text = request.POST.get('item' + str(i))
            self.add_choice(question.id, choice_text)
            i += 1

        return redirect(reverse('home', ))

    def add_choice(self, question_id, choice_text):
        try:
            question_to_add_choice = Question.objects.get(id=question_id)

        except (KeyError, Question.DoesNotExist):
            return redirect(reverse('polls:index'), {
                'error_message' : "Error in adding a choice"
            })

        else:
            Choice.objects.create(question=question_to_add_choice, choice_text=choice_text, votes=0)


class TryMustacheView(generic.View):
    def post(self, request, *args, **kwargs):
        questions = serializers.serialize('json', Question.objects.all())
        print questions
        # questions = Question.objects.all()
        # q = {
            # 'questions' : questions
        # }
        return JsonResponse({
            'questions' : questions
        })


    def get(self, request):
        questions = serializers.serialize('json', Question.objects.all())
        print questions
        context = {
            'questions' : questions
        }

        return JsonResponse({
            'questions' : questions
        })

        # return HttpResponse(json.dumps(context), 200)


class MainMustacheView(generic.TemplateView):

    template_name = 'polls/trymustache.html'

awesome_poll_site/templates/awesome_poll_site/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% block title %}{% endblock %}
    {% include 'awesome_poll_site/styles.html' %}
    {% include 'awesome_poll_site/scripts.html' %}
    {% block style %}{% endblock %}
</head>
<body>
    <div class="container">
        {% block nav %}{% endblock %}
        <div class="row">
            <div class="col"></div>
                <div class="col-6">
                    {% block content %}{% endblock %}
                </div>
            <div class="col"></div>
        </div>
    </div>
</body>

awesome_poll_site/templates/awesome_poll_site/navbar.html
{% extends 'awesome_poll_site/base.html' %}
{% load static %}

{% block nav %}
<nav class="navbar navbar-expand-lg bg-dark fixed-top">
    <div class="collapse navbar-collapse">
    <a href="{% url 'home' %}">
    <h4 class="bold-text form-signin-heading" style="color: white; font-family: 'Ultra', sans-serif; margin-left: 25px; margin-top: -3px; margin-bottom: -5px;">Polls</h4>
    </a>
    <h4 class="bold-text form-signin-heading" style="color: white; font-family: 'Ultra', sans-serif; margin-left: 1px; margin-top: 3px; font-size: 15px; margin-bottom: -5px;">.com</h4>
    <h6 class="bold-text form-signin-heading" style="color: white; font-family: 'Anonymous Pro', sans-serif; margin-left: 15px; margin-bottom: -11px; font-size: 14px;">| vote on all things</h6>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        </ul>
        <div class="dropdown">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsible">
            <span class="navbar-toggler-icon"></span>
        </button>

        <a href="{% url 'polls:add_poll' %}">
            <img src="{% static 'polls/images/addpoll.png' %}">  
        </a>
            {% if request.user.is_authenticated %}
            <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white;">
                {{ request.user }}
            </button>
            {% if user.profile.avatar %}
              <img class="center-cropped" src="{{ request.user.profile.avatar.url }}" width="24px" height="24px" style="border:none;">&nbsp;&nbsp;<span class="caret"></span>
            {% else %}
              <img class="center-cropped" src="{% static 'registration/images/default-user-avatar.jpg' %}" width="24px" height="24px" style="border:none;">&nbsp;&nbsp; <span class="caret"></span>
            {% endif %}
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'registration:edit_profile' %}">Edit Profile</a>
                <a class="dropdown-item" href="{% url 'registration:log_out' %}">Log out</a>
            </div>
            {% else %}
                <a href="{% url 'registration:log_in' %}" class="btn btn-primary">Log in</a>
            {% endif %}
        </div>
    </div>
</nav>
{% endblock %}

awesome_poll_site/templates/awesome_poll_site/scripts.html
{% load static %}

<!-- bootstrap popper is buggy with require so i had to load it manually -->

<script src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" 
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" 
            crossorigin="anonymous"></script>

<script src="{% static 'awesome_poll_site/js/require.js' %}"></script>
<script src="{% static 'awesome_poll_site/js/config.js' %}"></script>

<script>
    requirejs(['jquery', 'mustache', 'less'], 
        function($, Mustache) {

            console.log("loaded");
                
            // add choice in addpoll

            i = 2;
            $(document).ready(function() {
                $(".add-choice").click(function(){
                    console.log(i);
                    $(".choice-list").append('<li><input type="text" class="form-control col-lg-6" name="item' + i + '" id="textarea" placeholder="Choice" style="margin-bottom: 10px;" required=""></input></li>');
                    i++;
                });
            });

            // load questions

            // $(function() {
            //     console.log("hey!");
            //     var url = "{% url 'polls:try_mustache' %}";
            //     console.log(url);

            //     $.ajax({
            //         url: url, type: 'get', success: function (data) {
            //             // body...
            //             // data = JSON.parse(data);
            //             data = JSON.parse(data.questions);
            //             console.log(data);
            //             // var template = $('#questions-template').html();
            //             var info = Mustache.to_html(template, data);
            //             $('#questions').html(info);
            //         }
            //     });
            // });
            // console.log("hey");
    });    
</script>

awesome_poll_site/templates/awesome_poll_site/styles.html
{% load static %}

<link rel="shortcut icon" type="image/png" href="{% static 'awesome_poll_site/images/polls.png' %}"/>
<link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Anton|Hammersmith+One|Varela|Ultra|Anonymous+Pro" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

polls/templates/polls/addpoll.html
{% extends 'awesome_poll_site/navbar.html'%}
{% load static %}

{% block title%}
    <Title>Add Poll</Title>
{% endblock %}

{% block style %}
    <link rel="stylesheet/less" type="text/css" href="{% static 'polls/css/home.less' %}">
{% endblock %}

{% block content %}
    <form action="{% url 'polls:add_poll' %}" method="post">
        {% csrf_token %}
        <h4 class="bold-text form-signin-heading" style="font-family: 'Ultra', sans-serif; margin-left: 20px; margin-top: 3px; font-size: 30px; ">Question</h4>
        <input type="text" class="form-control col-lg-6" name="question_text" placeholder="Poll Question"></input><br>
        <h4 class="bold-text form-signin-heading" style="font-family: 'Ultra', sans-serif; margin-left: 20px; margin-top: 3px; font-size: 30px; ">Choices</h4>
        <ul style="list-style-type: none; padding: 0;" class="choice-list">
            <li>
                <input type="text" class="form-control col-lg-6" name="item0" id="textarea" placeholder="Choice" style="margin-bottom: 10px;" required=""></input>
            </li>
            <li>
                <input type="text" class="form-control col-lg-6" name="item1" id="textarea" placeholder="Choice" style="margin-bottom: 10px;" required=""></input>
            </li>
        </ul>
        <button type="button" class="btn bg-dark add-choice" style="color: white;">Add Item</button>
        <button type="submit" class="btn " style="background-color: rgb(90,254,61); color: white;">Post Poll</button>
    </form>

{% endblock %}

polls/templates/polls/index.html
{% extends 'awesome_poll_site/navbar.html' %}navbar

{% load static %}

{% block title %}
    <title>Home</title>
{% endblock %}

{% block style %}
    <link rel="stylesheet/less" type="text/css" href="{% static 'polls/css/home.less' %}">
{% endblock %}

{% block content %}
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <div class="card border-secondary mb-3" style="max-width: 20rem;">
                    <div class="card-header">
                        {% if user.profile.avatar %}
                            <img class="center-cropped" src="{{ request.user.profile.avatar.url }}" width="24px" height="24px" style="border:none;">&nbsp;&nbsp;{{ request.user.first_name }} <span class="caret"></span>
                        {% else %}
                            <img class="center-cropped" src="{% static 'registration/images/default-user-avatar.jpg' %}" width="27px" height="27px" style="border:none;">&nbsp;
                            <span class="caret"></span>
                        {% endif %}
                        {{ request.user.first_name }}
                        <span">
                            {{ question.user_who_asked }}
                        </span>
                        <br>
                        <small style="font-size: 10px; margin-left: 33px;">
                            {{ question.pub_date|date:'f A, M d Y D' }}
                        </small>
                    </div>
                <div class="card-body text-secondary">
                    <h4 class="card-title font-weight-bold" style="color: rgb(52,58,64);">{{ question.question_text }}</h4>
                    <ul class="list-group">
                        <form action="{% url 'polls:vote' question.id %}" method="POST">
                            {% csrf_token %}
                            {% for choice in question.choice_set.all %}
                                <li class="list-group-item">
                                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                                    {{ choice.choice_text }}
                                    <label for="choice{{ forloop.counter }}">
                                    </label>
                                </li>
                            {% endfor %}
                            <br>
                            <input type="submit"  class="btn btn-outline-secondary btn-block col-md-auto" value="Vote" /> 
                        </form>
                    </ul>
                  </div>
                </div>
            {% endfor %}
        </ul>

    {% else %}
        <p> No polls are available. </p>
        
    {% endif %}

{% endblock %}

polls/templates/polls/questions_mustache.html
<script id="questions-template" type="text/template">
    {{ #questions }}
        <li>question.question_text</li>
    {{ /questions }}
</script>

polls/templates/polls/results.html
{% extends 'awesome_poll_site/navbar.html' %}

{% load static %}

{% block title %}
    <title>{{ question.question_text }}</title>
{% endblock %}

{% block style %}
    <link rel="stylesheet/less" type="text/css" href="{% static 'polls/css/home.less' %}">
{% endblock %}

{% block script %}
    <script type="text/javascript" src="{% static 'polls/js/addchoice.js' %}"></script>
{% endblock%}

{% block content %}
    <h2 class="card-title font-weight-bold" style="color: rgb(52,58,64);">{{ question.question_text }}</h2>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes }} 
            vote{{ choice.votes|pluralize }}
        </li>
        {% endfor %}
        <br>
        {{ error_message }}
    </ul>

    <a href="{% url 'home' %}">Back to polls</a>

{% endblock %}

polls/templates/polls/trymustache.html
{% extends 'awesome_poll_site/base.html' %}
{% load static %}

{% block content %}

    <h2>List of questions</h2>
    <ul id="questions">
    </ul>

    <script>
       
    </script>

{% endblock %}

{% include 'polls/questions_mustache.html'%}